server:
  port: 84

spring:
  application:
    name: cloud-consumer-nacos-sentinel-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8088 #sentinel-dashboard地址
        port: 8719


management:
  endpoints:
    web:
      exposure:
        include: "*"