server:
  port: 84

spring:
  application:
    name: cloud-consumer-nacos-sentinel-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"