server:
  port: 80

spring:
  application:
    name: cloud-consumer-nacos-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"