server:
  port: 8003

spring:
  application:
    name: cloud-prodiver-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud_provider_payment?useUnicode=true&characterEncoding-utf-8&useSSL=false
    username: root
    password: root
    druid:
      test-while-idle: false
  cloud:
    zookeeper: #注册服务到zookeeper
      connect-string: localhost:2181


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml