server:
  port: 9527

spring:
  application:
    name: cloud-gateway9527
  cloud:
    gateway:
      routes:
        - id: payment_routh_1   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8005  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/list/1   # 断言，路径相匹配的进行路由
        - id: payment_routh_2
          uri: lb://cloud-prodiver-service
          predicates:
            - Path=/payment/timeout
        - id: payment_routh_3   #动态路由
          uri: lb://cloud-prodiver-service
          predicates:
            - Path=/payment/list


eureka:
  client:
    register-with-eureka: true #是否将自己注册进入到eureka
    fetch-registry: true #是否从注册中心拉取服务信息
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka
      # 集群版
  #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway9527 #更新主机名称
    prefer-ip-address: true #显示IP地址
    #Eureka 客户端同服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待的时间上限，单位为秒（默认是90秒）超时将剔除服务
    lease-expiration-duration-in-seconds: 2